import { Sulphur_Point } from "next/font/google";
import { SessionProvider } from 'next-auth/react';

import "./globals.css";

// Configure Sulphur Point font
const sulphurPoint = Sulphur_Point({
  weight: ["300", "400", "700"], // Available weights for Sulphur Point
  variable: "--font-sulphur-point",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sulphurPoint.variable} antialiased`}>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}